### ISSUE TITLE
Issue with API's

### ISSUE THREAD

**Issue by prathimapramod** [AdithyaBhat17/take-home-assignment#14]
Since the URl for api's should have localhost:8080
Should we have our tomcat up and running
As I am using an old laptop and does not host much RAM it is difficult for me to have multiple applications running at the same time.
Hence please request you to give a solution to have this api running for any port number.
Thank you

**Comment by AdithyaBhat17** [comment]
Hi, please follow the following steps to get the APIs up and running on http://localhost:8080/
- `cd server/`
- `echo 'IRON_KEY  = <enter a 32 character password here>' >> .env`
- `yarn && yarn run dev` or `npm install && npm run dev` based on your preferred package manager.

**Comment by AdithyaBhat17** [comment]
@prathimapramod 

You can change the port by making a small change at `server/src/index.js`

https://github.com/AdithyaBhat17/take-home-assignment/blob/0c5cd807136360ab3911d570418a158af002be18/server/src/index.js#L16

Replace 8080 with any other port on line 16.
