### ISSUE TITLE
still getting cors error Please help

### ISSUE THREAD

**Issue by prathimapramod** [AdithyaBhat17/take-home-assignment#21]
![cors_error](https://user-images.githubusercontent.com/70502524/95720063-5e2f9c80-0c8e-11eb-9f11-01462b8ee14c.PNG)
I have started my server on 8080 and api's run but my app runs in port 3000
so I am getting cors error please help
I also tried changing server to port 3000 ,and this time the app changes its port to 3001

**Comment by AdithyaBhat17** [comment]
You can use this extension to resolve this cors issue for now https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en

**Comment by prathimapramod** [comment]
I am using this extension but still getting the cors issue

**Comment by AdithyaBhat17** [comment]
Did you enable the extension? Please share a screenshot

**Comment by prathimapramod** [comment]
sorry I just enabled it.The cors error does not occur now but I am not getting the response.It says undefined
    On Monday, October 12, 2020, 01:39:51 PM GMT+5:30, Adithya NR <notifications@github.com> wrote:  
 
 


Did you enable the extension? Please share a screenshot

**Comment by AdithyaBhat17** [comment]
Please go through the API documentation. I think you've missed some parameters or headers

**Comment by prathimapramod** [comment]
no sir/api/register does not have any request headers
    On Monday, October 12, 2020, 01:44:36 PM GMT+5:30, Adithya NR <notifications@github.com> wrote:  
 
 


Closed #21.

**Comment by AdithyaBhat17** [comment]
Did you add
`IRON_KEY = <any 32 character string>` 
at /server/.env file?

**Comment by prathimapramod** [comment]
Yes

Sent from Yahoo Mail on Android 
 
  On Mon, 12 Oct 2020 at 5:08 pm, Adithya NR<notifications@github.com> wrote:   


Did you add
IRON_KEY = <any 32 character string>
at /server/.env file?

**Comment by prathimapramod** [comment]
Please help me on this sir.As HR is asking to submit soon sir
    On Monday, October 12, 2020, 05:12:00 PM GMT+5:30, Prathima S R <prathima5raj@yahoo.com> wrote:  
 
 Yes

Sent from Yahoo Mail on Android 
 
  On Mon, 12 Oct 2020 at 5:08 pm, Adithya NR<notifications@github.com> wrote:   


Did you add
IRON_KEY = <any 32 character string>
at /server/.env file?

**Comment by prathimapramod** [comment]
response is coming as not defined    On Monday, October 12, 2020, 05:21:46 PM GMT+5:30, Prathima S R <prathima5raj@yahoo.com> wrote:  
 
  Please help me on this sir.As HR is asking to submit soon sir
    On Monday, October 12, 2020, 05:12:00 PM GMT+5:30, Prathima S R <prathima5raj@yahoo.com> wrote:  
 
 Yes

Sent from Yahoo Mail on Android 
 
  On Mon, 12 Oct 2020 at 5:08 pm, Adithya NR<notifications@github.com> wrote:   


Did you add
IRON_KEY = <any 32 character string>
at /server/.env file?

**Comment by AdithyaBhat17** [comment]
Please share your GitHub repository link. I'll try to find what the issue is.

**Comment by prathimapramod** [comment]
yes sirI am sending the link
prathimapramod/betsol



| 
| 
| 
|  |  |

 |

 |
| 
|  | 
prathimapramod/betsol

Contribute to prathimapramod/betsol development by creating an account on GitHub.
 |

 |

 |




    On Monday, October 12, 2020, 05:40:21 PM GMT+5:30, Adithya NR <notifications@github.com> wrote:  
 
 


Please share your GitHub repository link. I'll try to find what the issue is.

**Comment by prathimapramod** [comment]
Please let me knowThank You
| 
| 
| 
|  |  |

 |

 |
| 
|  | 
prathimapramod/betsol

Contribute to prathimapramod/betsol development by creating an account on GitHub.
 |

 |

 |




    On Monday, October 12, 2020, 07:09:45 PM GMT+5:30, Prathima S R <prathima5raj@yahoo.com> wrote:  
 
  yes sirI am sending the link
prathimapramod/betsol



| 
| 
| 
|  |  |

 |

 |
| 
|  | 
prathimapramod/betsol

Contribute to prathimapramod/betsol development by creating an account on GitHub.
 |

 |

 |




    On Monday, October 12, 2020, 05:40:21 PM GMT+5:30, Adithya NR <notifications@github.com> wrote:  
 
 


Please share your GitHub repository link. I'll try to find what the issue is.

**Comment by AdithyaBhat17** [comment]
Hi, the reason for the issues you are facing is because you are sending the request in the form `data: { email: 'email', password: 'password'}` instead of `{email: 'email', password: 'password'}`.

![image](https://user-images.githubusercontent.com/20818481/95754529-d0b97000-0cc0-11eb-88be-97b89b7dd593.png)

**Comment by prathimapramod** [comment]
How are we supposed to send from function sir?

Sent from Yahoo Mail on Android 
 
  On Mon, 12 Oct 2020 at 7:27 pm, Adithya NR<notifications@github.com> wrote:   


Hi, the reason for the issues you are facing is because you are sending the request in the form data: { email: 'email', password: 'password'} instead of {email: 'email', password: 'password'}.

**Comment by AdithyaBhat17** [comment]
You'll have to figure it out on your own I'm sorry.

**Comment by prathimapramod** [comment]
Hi,I am sending only {email:"email",password:"password"}still getting this issue sirPLease helpThank you
    On Monday, October 12, 2020, 07:31:34 PM GMT+5:30, Adithya NR <notifications@github.com> wrote:  
 
 


You'll have to figure it out on your own I'm sorry.

**Comment by prathimapramod** [comment]
Hi sir,Please let me know
    On Monday, October 12, 2020, 08:04:32 PM GMT+5:30, Prathima S R <prathima5raj@yahoo.com> wrote:  
 
  Hi,I am sending only {email:"email",password:"password"}still getting this issue sirPLease helpThank you
    On Monday, October 12, 2020, 07:31:34 PM GMT+5:30, Adithya NR <notifications@github.com> wrote:  
 
 


You'll have to figure it out on your own I'm sorry.
